import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { IoExpandOutline } from "react-icons/io5";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";
import { PageIntro } from "@/components/site-shell";
import feast from "@/assets/traditional-feast.jpg"; import wedding from "@/assets/wedding-banquet.jpg"; import platters from "@/assets/corporate-platters.jpg"; import cake from "@/assets/celebration-cake.jpg"; import treats from "@/assets/baked-treats.jpg"; import hero from "@/assets/nanaka-hero.jpg";

export const Route=createFileRoute("/gallery")({head:()=>({meta:[{title:"Gallery | Nana'kaJobe Catering & Baking"},{name:"description",content:"Explore Nana'kaJobe's traditional dishes, buffets, celebration cakes, baked treats and event setups."},{property:"og:title",content:"Our Food & Celebrations | Nana'kaJobe"},{property:"og:description",content:"A gallery of generous feasts, elegant events and joyful baking."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Gallery});
const photos=[{src:feast,cat:"Traditional Dishes",title:"A feast from home",alt:"Traditional beef stew and sides"},{src:hero,cat:"Event Setups",title:"Gathered in celebration",alt:"Guests sharing a Zulu feast"},{src:platters,cat:"Platters & Buffets",title:"Conference spread",alt:"Gourmet corporate platter"},{src:cake,cat:"Cakes & Treats",title:"Golden celebration",alt:"Gold and chocolate drip cake"},{src:wedding,cat:"Event Setups",title:"A beautiful Umembeso",alt:"Zulu traditional wedding banquet"},{src:treats,cat:"Cakes & Treats",title:"Sweet favourites",alt:"Scones and coconut snowballs"}];
function Gallery(){const [filter,setFilter]=useState("All");const [open,setOpen]=useState<(typeof photos)[number]|null>(null);const cats=["All","Traditional Dishes","Platters & Buffets","Cakes & Treats","Event Setups"];const shown=filter==="All"?photos:photos.filter(p=>p.cat===filter);return <><PageIntro eyebrow="Gallery" title="Food, family and unforgettable moments.">A taste of the tables we set, the treats we bake and the celebrations we are honoured to serve.</PageIntro><section className="px-5 py-16 lg:px-8 lg:py-24"><div className="mx-auto max-w-[1600px]"><div className="flex gap-2 overflow-x-auto pb-6">{cats.map(c=><Button key={c} variant={filter===c?"default":"outline"} onClick={()=>setFilter(c)} className="shrink-0">{c}</Button>)}</div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{shown.map((p,i)=><button key={p.title} onClick={()=>setOpen(p)} className={`group relative overflow-hidden text-left ${i===0?"sm:col-span-2 lg:col-span-2":""}`}><img src={p.src} alt={p.alt} width={1200} height={912} loading="lazy" className={`w-full object-cover transition-transform duration-700 group-hover:scale-105 ${i===0?"aspect-[2/1]":"aspect-[4/3]"}`}/><span className="absolute inset-0 bg-gradient-to-t from-primary/85 via-transparent to-transparent"/><span className="absolute bottom-0 flex w-full items-end justify-between p-5 text-primary-foreground"><span><span className="block text-xs font-bold uppercase tracking-[0.15em] text-gold">{p.cat}</span><span className="mt-1 block font-display text-2xl">{p.title}</span></span><span className="grid size-9 place-items-center border border-primary-foreground/40"><IoExpandOutline className="size-4"/></span></span></button>)}</div></div></section><Dialog open={!!open} onOpenChange={v=>!v&&setOpen(null)}><DialogContent className="max-w-5xl border-0 bg-primary p-2 text-primary-foreground"><DialogTitle className="sr-only">{open?.title}</DialogTitle><DialogDescription className="sr-only">Expanded gallery image</DialogDescription>{open&&<img src={open.src} alt={open.alt} width={1200} height={912} className="max-h-[82vh] w-full object-contain"/>}</DialogContent></Dialog></>}
